# Generated by Django 6.0.4 on 2026-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhome', 'Townhome')], max_length=20)),
                ('status', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('sqft', models.PositiveIntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('images', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
