# Generated by Django 6.0.4 on 2026-05-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_blogparagraphoverride_propertyparagraphoverride'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteControl',
        ),
    ]
