# Generated by Django 6.0.4 on 2026-05-04 11:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_seed_blog_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogparagraphoverride',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='propertyparagraphoverride',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
