# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_alter_blogparagraphoverride_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('points', models.JSONField(default=list)),
                ('image_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('about', 'About Us'), ('why_us', 'Why Choose Us'), ('services', 'What We Do')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Prime Estates', max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('hero_title', models.CharField(default='WELCOME TO REALTOR', max_length=255)),
                ('hero_bg_image', models.URLField(default='https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1920&q=80')),
                ('phone', models.CharField(default='+01 123 456 78', max_length=20)),
                ('email', models.EmailField(default='info@realtor.com', max_length=254)),
                ('address', models.TextField(default='123 Real Estate Ave, Luxury City, ST 12345')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('about_title', models.CharField(default='We Are The Best Real Estate Company In The Region', max_length=255)),
                ('about_description_1', models.TextField(blank=True)),
                ('about_description_2', models.TextField(blank=True)),
                ('about_main_image', models.URLField(default='https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80')),
                ('experience_years', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('avatar_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
