# Generated by Django 6.0.4 on 2026-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_abouttab_contactmessage_feature_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('shield', 'Shield'), ('users', 'Users / Agents'), ('clock', 'Clock / Time'), ('home', 'Home'), ('star', 'Star'), ('check', 'Check')], default='shield', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stat_number', models.CharField(help_text='e.g. 2,500+', max_length=20)),
                ('stat_label', models.CharField(help_text='e.g. PROPERTIES LISTED', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Feature',
                'verbose_name_plural': 'Why Choose Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='WHY CHOOSE US', max_length=100)),
                ('heading', models.CharField(default='Why Choose Prime Estates?', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Section Header',
            },
        ),
    ]
