# Generated by Django 6.0.4 on 2026-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_whychoosefeature_whychoosesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='count_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
