# Generated by Django 6.0.4 on 2026-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_feature_count_feature_count_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_checklist',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of checklist strings, e.g. ["Verified Properties", "Expert Agents", "Transparent Pricing"]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stats',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of stat objects, e.g. [{"value": "12K+", "label": "Properties"}, {"value": "7.5K+", "label": "Happy Clients"}]'),
        ),
    ]
