# Generated by Django 6.0.4 on 2026-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_sitesettings_about_stats_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_banner_title',
            field=models.CharField(default='About Us', help_text='Large heading shown on the About page banner.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agents_section_heading',
            field=models.CharField(default='Our Great Agents', help_text='Heading for the team/agents section.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agents_section_subtitle',
            field=models.CharField(blank=True, default='Meet the experienced professionals dedicated to finding your perfect property.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_label',
            field=models.CharField(default='Just Contact Us', help_text='Label for the CTA button.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_heading',
            field=models.CharField(default='Do you want to sell your property?', help_text='Heading text for the green CTA banner.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_subtext',
            field=models.CharField(blank=True, default="Call us and list your property here. We'll find the right buyer for you quickly.", help_text='Subtitle text below the CTA heading.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='purpose_section_heading',
            field=models.CharField(default='Our Purpose', help_text="Heading for the tabbed 'Our Purpose' section.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='purpose_section_subtitle',
            field=models.CharField(blank=True, default='Discover what drives us every single day.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_section_heading',
            field=models.CharField(default='What We Do', help_text="Heading for the 'What We Do' features section.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_section_subtitle',
            field=models.CharField(blank=True, default='Comprehensive real estate services tailored to your needs.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_section_heading',
            field=models.CharField(default='What Our Clients Say', help_text='Heading for the testimonials section.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_section_subtitle',
            field=models.CharField(blank=True, default='Real stories from real people who found their perfect homes with us.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_we_are_heading',
            field=models.CharField(default='Who We Are', help_text="Section heading for the 'Who We Are' block.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_us_eyebrow',
            field=models.CharField(default='Why Choose Us', help_text="Small label above the 'Why Choose Us' heading.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_us_heading',
            field=models.CharField(default='The Right Choice For All Your Real Estate Needs', help_text="Main heading for the 'Why Choose Us' section.", max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_us_image',
            field=models.URLField(default='https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80', help_text="Image shown on the left side of the 'Why Choose Us' section."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_checklist',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Verified Properties", "Expert Agents", "Transparent Pricing"]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_description_1',
            field=models.TextField(blank=True, default='With over 15 years of experience, Realtor has helped thousands of families find their perfect homes across the region.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_description_2',
            field=models.TextField(blank=True, default='We believe property hunting should be exciting, not stressful. From your first inquiry to closing day, we provide personalized guidance every step of the way.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_stats',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"value": "12K+", "label": "Properties"}, {"value": "7.5K+", "label": "Happy Clients"}]'),
        ),
    ]
