# Generated by Django 6.0.4 on 2026-05-08 16:39

from django.db import migrations, models


DEFAULT_TESTIMONIALS = [
    {
        "name": "Sarah Johnson",
        "role": "Home Buyer",
        "text": (
            "Prime Estates made finding our dream home an absolute pleasure. "
            "Their team was professional, responsive, and genuinely cared about "
            "what we were looking for. We couldn't be happier with our new home!"
        ),
        "rating": 5,
        "avatar_url": "https://randomuser.me/api/portraits/women/44.jpg",
        "order": 1,
        "is_active": True,
    },
    {
        "name": "Michael Chen",
        "role": "Property Investor",
        "text": (
            "I've worked with many real estate agencies over the years, but Prime Estates "
            "stands out for their market knowledge and transparency. They helped me secure "
            "three investment properties at excellent prices."
        ),
        "rating": 5,
        "avatar_url": "https://randomuser.me/api/portraits/men/32.jpg",
        "order": 2,
        "is_active": True,
    },
    {
        "name": "Emily Rodriguez",
        "role": "First-Time Buyer",
        "text": (
            "As a first-time buyer I was nervous about the whole process, but the team "
            "walked me through every step with patience and clarity. I found my perfect "
            "apartment within two weeks. Highly recommend!"
        ),
        "rating": 5,
        "avatar_url": "https://randomuser.me/api/portraits/women/68.jpg",
        "order": 3,
        "is_active": True,
    },
]


def seed_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("myproject", "Testimonial")
    # Only seed if the table is empty to avoid duplicates on re-run
    if not Testimonial.objects.exists():
        for data in DEFAULT_TESTIMONIALS:
            Testimonial.objects.create(**data)


def unseed_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("myproject", "Testimonial")
    names = [t["name"] for t in DEFAULT_TESTIMONIALS]
    Testimonial.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_sitesettings_about_all_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Uncheck to hide this testimonial from the website without deleting it.',
            ),
        ),
        migrations.RunPython(seed_testimonials, reverse_code=unseed_testimonials),
    ]
