# Generated by Django 6.0.4 on 2026-05-09 06:25

from django.db import migrations, models


QUICK_LINKS = [
    {"label": "Home",       "href": "/",           "order": 1},
    {"label": "About Us",   "href": "/about",      "order": 2},
    {"label": "Properties", "href": "/properties", "order": 3},
    {"label": "Blog",       "href": "/blog",       "order": 4},
    {"label": "Contact",    "href": "/contact",    "order": 5},
]

PROPERTY_LINKS = [
    {"label": "Buy Property",      "href": "/buy",        "order": 1},
    {"label": "Rent Property",     "href": "/rent",       "order": 2},
    {"label": "Sell Property",     "href": "/sell",       "order": 3},
    {"label": "Featured Listings", "href": "/properties", "order": 4},
]


def seed_footer_links(apps, schema_editor):
    NavItem = apps.get_model("myproject", "NavItem")
    # Only seed if no footer links exist yet
    if not NavItem.objects.filter(section__in=["quick_links", "properties"]).exists():
        for item in QUICK_LINKS:
            NavItem.objects.create(section="quick_links", is_active=True, **item)
        for item in PROPERTY_LINKS:
            NavItem.objects.create(section="properties", is_active=True, **item)


def unseed_footer_links(apps, schema_editor):
    NavItem = apps.get_model("myproject", "NavItem")
    NavItem.objects.filter(section__in=["quick_links", "properties"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_testimonial_is_active_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='section',
            field=models.CharField(
                choices=[
                    ('navbar',      'Navbar'),
                    ('quick_links', 'Footer – Quick Links'),
                    ('properties',  'Footer – Properties'),
                ],
                default='navbar',
                help_text='Which part of the site this link belongs to.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_heading',
            field=models.CharField(default='Contact', help_text='Column heading for the Contact info section.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_extra',
            field=models.CharField(blank=True, default='All rights reserved', help_text='Text after the year and site name in the copyright line.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_button',
            field=models.CharField(default='Subscribe', help_text='Button label for the newsletter subscription.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_heading',
            field=models.CharField(default='Subscribe to our newsletter', help_text='Heading text in the newsletter strip at the top of the footer.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_office_hours',
            field=models.CharField(default='Mon-Fri: 9:00 - 18:00', help_text='Office hours line shown in the footer contact column.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_properties_heading',
            field=models.CharField(default='Properties', help_text='Column heading for the Properties links section.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_quick_links_heading',
            field=models.CharField(default='Quick Links', help_text='Column heading for the Quick Links section.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.TextField(
                blank=True,
                default='Your trusted partner in finding the perfect property. We combine smart discovery tools with responsive support.',
                help_text='Short description shown under the logo in the footer.',
            ),
        ),
        migrations.RunPython(seed_footer_links, reverse_code=unseed_footer_links),
    ]
