# Generated by Django 6.0.4 on 2026-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_footer_fields_and_navitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_label',
            field=models.CharField(default='Our Office', help_text='Label for the address card.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_banner_bg',
            field=models.URLField(blank=True, default='', help_text='Background image URL for the Contact page banner. Leave blank to use the default dark colour.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_banner_eyebrow',
            field=models.CharField(default='Get In Touch', help_text='Small label above the heading on the Contact page banner.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_banner_heading',
            field=models.CharField(default='Contact Us', help_text='Main heading on the Contact page banner.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_banner_subtitle',
            field=models.CharField(blank=True, default='Send your details and message. We will get back to you shortly.', help_text='Subtitle text below the heading on the Contact page banner.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_label',
            field=models.CharField(default='Email Address', help_text='Label for the email card.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_button_label',
            field=models.CharField(default='Send Message', help_text='Submit button label.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_email_label',
            field=models.CharField(default='Email Address', help_text='Label for the Email field.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_error_msg',
            field=models.CharField(default='Something went wrong. Please try again or contact us directly.', help_text='Message shown when form submission fails.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_heading',
            field=models.CharField(default='Send Us a Message', help_text='Heading inside the contact form card.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_message_label',
            field=models.CharField(default='Your Message', help_text='Label for the Message field.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_name_label',
            field=models.CharField(default='Full Name', help_text='Label for the Name field.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_phone_label',
            field=models.CharField(default='Phone Number', help_text='Label for the Phone field.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_subject_label',
            field=models.CharField(default='Subject', help_text='Label for the Subject field.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_subtext',
            field=models.CharField(blank=True, default='Fill in the form below and our team will get back to you within 24 hours.', help_text='Subtitle inside the contact form card.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_success_msg',
            field=models.CharField(default='Thank you! Your message has been sent. We will get back to you shortly.', help_text='Message shown after successful form submission.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_label',
            field=models.CharField(default='Working Hours', help_text='Label for the hours card.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_value',
            field=models.CharField(default='Mon – Fri: 9:00 AM – 6:00 PM', help_text='Working hours text shown in the hours card.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_map_embed_url',
            field=models.URLField(blank=True, default='', help_text='Google Maps embed URL. Go to Google Maps → Share → Embed a map → copy the src URL.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_label',
            field=models.CharField(default='Phone Number', help_text='Label for the phone card.', max_length=80),
        ),
    ]
