# Generated by Django 6.0.4 on 2026-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_sitesettings_contact_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='properties_banner_bg',
            field=models.URLField(blank=True, default='', help_text='Background image URL for the Properties page banner. Leave blank to use the default dark colour.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_banner_eyebrow',
            field=models.CharField(default='Browse Listings', help_text='Small label above the heading on the Properties page banner.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_banner_heading',
            field=models.CharField(default='Properties', help_text='Main heading on the Properties page banner.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_banner_subtitle',
            field=models.CharField(blank=True, default='Filter by city, type, status, and price range to find your perfect property.', help_text='Subtitle text on the Properties page banner.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_empty_heading',
            field=models.CharField(default='No properties found for the selected filters.', help_text='Heading shown when no properties match the filters.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_empty_subtext',
            field=models.CharField(blank=True, default='Try adjusting your search criteria.', help_text='Subtext shown when no properties match.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_filter_button_label',
            field=models.CharField(default='Filter', help_text='Label for the filter submit button.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_filter_city_placeholder',
            field=models.CharField(default='All cities', help_text='Default option text for the city filter.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_filter_max_placeholder',
            field=models.CharField(default='Max price', help_text='Placeholder for the max price input.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_filter_min_placeholder',
            field=models.CharField(default='Min price', help_text='Placeholder for the min price input.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_filter_status_placeholder',
            field=models.CharField(default='All status', help_text='Default option text for the status filter.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='properties_filter_type_placeholder',
            field=models.CharField(default='All types', help_text='Default option text for the type filter.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='property_buy_button_label',
            field=models.CharField(default='Buy Now – Pay with Khalti', help_text='Label for the Buy Now button.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='property_buy_card_heading',
            field=models.CharField(default='Ready to Buy?', help_text='Heading for the Khalti buy card on the detail page.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='property_buy_card_subtext',
            field=models.CharField(blank=True, default="Pay securely via Khalti. You will be redirected to Khalti's payment page.", help_text='Subtext inside the buy card.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='property_detail_amenities_heading',
            field=models.CharField(default='Amenities', help_text='Heading for the amenities list.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='property_detail_eyebrow',
            field=models.CharField(default='Property Details', help_text='Small label above the property title on the detail page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='property_detail_section_heading',
            field=models.CharField(default='Property Details', help_text='Heading for the property description card.', max_length=100),
        ),
    ]
